In [57]:
import pandas as pd
import random as rd
import warnings
warnings.filterwarnings('ignore')

In [84]:
path = "C:\\Users\\ritaf\\Documents\\ESTUDOS\\NOVA IMS\\3ยบ Ano\\Capstone Project\\Projeto\\"
appointment = pd.read_csv(path + 'no_show.csv')
customer = pd.read_csv(path + 'customer_data.csv')
hdi = pd.read_excel(path + 'HDI.xls')

In [85]:
hdi.dropna(inplace=True)
hdi = hdi.rename(columns={'Human Development Index (HDI) ': 'HDI'})
hdi = hdi.sort_values(by='Country')
hdi_dict = pd.Series(hdi['Country'].values, index=hdi['HDI']).to_dict()
# hdi_dict

In [34]:
appointment = appointment.sample(n=150, replace=False)

In [35]:
# TEM O APPOINTMENT ID A MAIS
features = ['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI (Year-1)']
appointment = appointment.loc[:, features]
appointment.head()

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,AppointmentChanges,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1)
9255,10862,30,18,21.00,1,2,3,0.0,0,0,...,0,88,0,2,0,1,3,96.90,0.0,0.918
10783,23241,10,3,20.50,0,3,2,0.0,0,0,...,3,60,0,1,0,1,3,87.30,0.0,0.876
6652,14664,7,10,21.50,7,19,2,0.0,0,0,...,0,29,0,0,0,0,6,68.34,0.0,0.572
5582,12870,38,14,23.75,2,4,2,0.0,0,0,...,0,120,0,0,0,1,6,129.60,0.0,0.743
8229,20881,38,11,22.75,2,0,2,0.0,0,0,...,0,24,1,1,0,1,3,142.00,0.0,0.898

In [36]:
appointment.reset_index(drop=True, inplace=True)

In [37]:
complete = pd.concat([appointment, customer], axis=1)
complete

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1),PatientID,FirstName,LastName,Email,Age,Username
0,10862,30,18,21.00,1,2,3,0.0,0,0,...,3,96.90,0.0,0.918,1,John,Doe,johndoe@email.com,35,johndoe35
1,23241,10,3,20.50,0,3,2,0.0,0,0,...,3,87.30,0.0,0.876,2,Jane,Smith,janesmith@email.com,28,janesmith28
2,14664,7,10,21.50,7,19,2,0.0,0,0,...,6,68.34,0.0,0.572,3,Robert,Johnson,robertjohnson@email.com,42,robjohn42
3,12870,38,14,23.75,2,4,2,0.0,0,0,...,6,129.60,0.0,0.743,4,Alice,Williams,alicewilliams@email.com,31,alicewilliams31
4,20881,38,11,22.75,2,0,2,0.0,0,0,...,3,142.00,0.0,0.898,5,Michael,Brown,michaelbrown@email.com,45,mikebrown45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,39288,45,2,14.75,0,1,1,0.0,0,0,...,6,100.00,0.0,0.885,146,Karen,Martin,karenmartin@email.com,45,karenm45
146,29865,23,3,20.50,0,2,1,0.0,0,0,...,6,0.00,0.0,0.842,147,Joseph,Anderson,josephanderson@email.com,36,josepha36
147,27422,27,27,18.50,1,2,2,0.0,0,0,...,6,101.10,0.0,0.920,148,Laura,Perez,lauraperez@email.com,31,laurap31
148,39911,34,18,19.25,1,3,2,0.0,0,0,...,6,80.50,0.0,0.876,149,William,Jones,williamjones@email.com,47,williamj47
149,22000,35,27,17.00,2,1,2,0.0,0,0,...,6,85.50,0.0,0.876,150,Mary,Hill,maryhill@email.com,32,maryh32

In [38]:
complete.columns

Index(['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth',
       'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults',
       'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments',
       'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking',
       'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked',
       'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult',
       'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance',
       'CountryofOriginHDI (Year-1)', 'PatientID', 'FirstName', 'LastName',
       'Email', 'Age', 'Username'],
      dtype='object')

In [39]:
patients = complete[['PatientID', 'FirstName', 'LastName', 'Email', 'Age', 'Username', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI (Year-1)']]

In [47]:
appointments = complete[['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI (Year-1)', 'PatientID']]

In [52]:
appointments.sort_values(by=['AppointmentID'], inplace=True)
appointments.reset_index(drop=True, inplace=True)
appointments.drop(columns=['AppointmentID'], inplace=True)
appointments

,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,PreviousAppointments,...,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1),PatientID
0,33,8,23.25,1,4,2,0.0,0,0,0,...,128,0,0,0,1,6,119.70,0.0,0.898,140
1,23,29,18.25,2,1,2,0.0,0,0,0,...,16,0,1,0,1,6,112.33,0.0,0.743,102
2,53,29,19.00,0,3,2,1.0,0,0,0,...,193,0,0,0,1,1,160.20,0.0,0.757,141
3,38,17,16.50,2,2,2,0.0,0,0,0,...,115,0,0,0,0,6,106.92,0.0,0.743,52
4,5,25,15.25,1,1,1,0.0,0,0,1,...,0,0,0,0,1,6,40.00,0.0,0.842,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,23,30,19.00,1,2,2,0.0,0,0,0,...,92,0,0,0,1,6,101.52,0.0,0.918,14
146,4,19,22.50,0,4,1,0.0,0,0,0,...,151,0,0,0,1,6,70.75,0.0,0.805,8
147,45,2,14.75,0,1,1,0.0,0,0,0,...,14,0,1,0,0,6,100.00,0.0,0.885,146
148,34,18,19.25,1,3,2,0.0,0,0,0,...,217,0,1,0,2,6,80.50,0.0,0.876,149
149,31,26,23.75,0,4,2,0.0,0,0,0,...,88,0,0,0,1,6,72.25,0.0,0.898,53

In [54]:
patients.drop(columns=['PatientID'], inplace=True)

In [55]:
# Export the DataFrame to a CSV file
appointments.to_csv(path + 'appointments.csv', index=True)
patients.to_csv(path + 'patients.csv', index=True)

NOTAS:
- children estรก como float, nรฃo sei se isso vai ser um problema
- appointment hour estรก tipo: 17.75 que รฉ 17h45
- para chegarmos ao appointment week number atravรฉs da data
    - date_object = datetime.strptime(date_string, '%Y-%m-%d')
    - week_number = date_object.strftime('%W')    o chatgpt disse %V
- id dos medicos รฉ um bocado estranho... por haver -1
- hdi temos de fazer a conversรฃo ... acho que pode ser logo no botรฃo... "se ele escolher isto, isto acontece2 com um if
- temos de aplicar robust scaler nas previsรตes
- dados perguntados ou nรฃo ao utilizador:
    - Sim: 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'ParkingSpaceBooked', 'SpecialRequests', 'DoctorAssigned', '%PaidinAdvance'
    - Nรฃo (jรก temos): 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI (Year-1)'? , 'PatientID'
    - Nรฃo (calculados): 'ConsultPriceEuros', 'OnlineBooking', 'BookingToConsultDays', 'AppointmentChanges', 'CountryofOriginHDI (Year-1)'?




Household adults 
Household children 
Household babies
Want to have a ficha?
Have insurance?
Nationality