In [1]:
import pandas as pd
import random as rd
import warnings
warnings.filterwarnings('ignore')

In [14]:
path = "C:\\Users\\ritaf\\Documents\\ESTUDOS\\NOVA IMS\\3ยบ Ano\\Capstone Project\\Projeto\\"
appointment = pd.read_csv(path + 'no_show.csv')
customer = pd.read_csv(path + 'customer_data.csv')

In [15]:
appointment = appointment.sample(n=150, replace=False)

In [16]:
# TEM O APPOINTMENT ID A MAIS
features = ['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI (Year-1)']
appointment = appointment.loc[:, features]
appointment.head()

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,AppointmentChanges,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1)
7447,39447,37,6,19.25,0,5,1,0.0,0,0,...,0,230,0,0,0,1,6,111.00,0.0,0.842
13693,35891,50,8,21.50,0,1,2,0.0,0,0,...,0,71,0,1,0,0,6,79.20,0.0,0.918
2313,21065,4,18,22.00,1,4,1,0.0,0,0,...,2,150,0,0,0,1,6,80.00,0.0,0.842
9675,15297,45,30,23.00,2,1,2,0.0,0,0,...,0,154,0,2,0,1,3,104.10,0.0,0.913
4801,37031,42,12,21.25,0,3,2,0.0,0,0,...,0,2,0,0,0,1,3,163.33,0.0,0.885

In [20]:
appointment.reset_index(drop=True, inplace=True)

In [23]:
complete = pd.concat([appointment, customer], axis=1)
complete

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1),PatientID,FirstName,LastName,Email,Age,Username
0,39447,37,6,19.25,0,5,1,0.0,0,0,...,6,111.00,0.0,0.842,1,John,Doe,johndoe@email.com,35,johndoe35
1,35891,50,8,21.50,0,1,2,0.0,0,0,...,6,79.20,0.0,0.918,2,Jane,Smith,janesmith@email.com,28,janesmith28
2,21065,4,18,22.00,1,4,1,0.0,0,0,...,6,80.00,0.0,0.842,3,Robert,Johnson,robertjohnson@email.com,42,robjohn42
3,15297,45,30,23.00,2,1,2,0.0,0,0,...,3,104.10,0.0,0.913,4,Alice,Williams,alicewilliams@email.com,31,alicewilliams31
4,37031,42,12,21.25,0,3,2,0.0,0,0,...,3,163.33,0.0,0.885,5,Michael,Brown,michaelbrown@email.com,45,mikebrown45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,33018,14,29,15.75,0,4,2,2.0,0,0,...,1,216.00,0.0,0.918,146,Karen,Martin,karenmartin@email.com,45,karenm45
146,20664,48,23,15.75,0,4,2,0.0,0,0,...,6,88.40,0.0,0.933,147,Joseph,Anderson,josephanderson@email.com,36,josepha36
147,27443,15,5,19.50,0,3,3,0.0,0,0,...,3,105.00,0.0,0.913,148,Laura,Perez,lauraperez@email.com,31,laurap31
148,17909,40,25,19.75,2,2,3,0.0,0,0,...,3,144.76,0.0,0.918,149,William,Jones,williamjones@email.com,47,williamj47
149,15154,34,14,15.25,1,0,2,1.0,0,0,...,6,134.10,0.0,0.813,150,Mary,Hill,maryhill@email.com,32,maryh32

In [27]:
complete.columns

Index(['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth',
       'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults',
       'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments',
       'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking',
       'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked',
       'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult',
       'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance',
       'CountryofOriginHDI (Year-1)', 'PatientID', 'FirstName', 'LastName',
       'Email', 'Age', 'Username'],
      dtype='object')

In [26]:
patients = complete[['PatientID', 'FirstName', 'LastName', 'Email', 'Age', 'Username', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI (Year-1)']]

In [30]:
appointments = complete[['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI (Year-1)', 'PatientID']]
appointments.set_index('AppointmentID', inplace=True)

In [31]:
appointments

,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,PreviousAppointments,...,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI (Year-1),PatientID
AppointmentID,,,,,,,,,,,,,,,,,,,,,
39447,37,6,19.25,0,5,1,0.0,0,0,0,...,230,0,0,0,1,6,111.00,0.0,0.842,1
35891,50,8,21.50,0,1,2,0.0,0,0,0,...,71,0,1,0,0,6,79.20,0.0,0.918,2
21065,4,18,22.00,1,4,1,0.0,0,0,0,...,150,0,0,0,1,6,80.00,0.0,0.842,3
15297,45,30,23.00,2,1,2,0.0,0,0,0,...,154,0,2,0,1,3,104.10,0.0,0.913,4
37031,42,12,21.25,0,3,2,0.0,0,0,0,...,2,0,0,0,1,3,163.33,0.0,0.885,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33018,14,29,15.75,0,4,2,2.0,0,0,0,...,25,0,0,0,1,1,216.00,0.0,0.918,146
20664,48,23,15.75,0,4,2,0.0,0,0,0,...,67,0,2,0,1,6,88.40,0.0,0.933,147
27443,15,5,19.50,0,3,3,0.0,0,0,0,...,54,0,1,0,1,3,105.00,0.0,0.913,148
17909,40,25,19.75,2,2,3,0.0,0,0,0,...,43,0,1,0,2,3,144.76,0.0,0.918,149
15154,34,14,15.25,1,0,2,1.0,0,0,0,...,86,0,0,0,1,6,134.10,0.0,0.813,150

NOTAS:
- children estรก como float, nรฃo sei se isso vai ser um problema
- appointment hour estรก tipo: 17.75 que รฉ 17h45
- para chegarmos ao appointment week number atravรฉs da data
    - date_object = datetime.strptime(date_string, '%Y-%m-%d')
    - week_number = date_object.strftime('%W')    o chatgpt disse %V
- id dos medicos รฉ um bocado estranho... por haver -1
- hdi temos de fazer a conversรฃo ... acho que pode ser logo no botรฃo... "se ele escolher isto, isto acontece2 com um if
- temos de aplicar robust scaler nas previsรตes
- dados perguntados ou nรฃo ao utilizador:
    - Sim: 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'AppointmentChanges', 'ParkingSpaceBooked', 'SpecialRequests', 'DoctorAssigned', '%PaidinAdvance'
    - Nรฃo (jรก temos): 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI (Year-1)'? , 'PatientID'
    - Nรฃo (calculados): 'ConsultPriceEuros', 'OnlineBooking', 'BookingToConsultDays', 'CountryofOriginHDI (Year-1)'?