In [86]:
import pandas as pd
import random as rd
import warnings
warnings.filterwarnings('ignore')

In [87]:
path = "C:\\Users\\ritaf\\Documents\\ESTUDOS\\NOVA IMS\\3ยบ Ano\\Capstone Project\\Projeto\\"
appointment = pd.read_csv(path + 'no_show.csv')
customer = pd.read_csv(path + 'customer_data.csv')
hdi = pd.read_excel(path + 'HDI.xls')

In [88]:
appointment.rename(columns={'CountryofOriginHDI (Year-1)': 'CountryofOriginHDI'}, inplace=True)

In [89]:
hdi.dropna(inplace=True)
hdi = hdi.rename(columns={'Human Development Index (HDI) ': 'HDI'})
hdi = hdi.sort_values(by='Country')
hdi_dict = pd.Series(hdi['Country'].values, index=hdi['HDI']).to_dict()
# hdi_dict

In [90]:
appointment = appointment.sample(n=150, replace=False)

In [92]:
# TEM O APPOINTMENT ID A MAIS
features = ['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI']
appointment = appointment.loc[:, features]
appointment.head()

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,AppointmentChanges,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI
280,32310,50,10,20.00,1,1,1,0.0,0,0,...,0,89,0,2,0,1,6,96.00,0.0,0.876
11503,13182,47,16,20.25,2,4,2,0.0,0,0,...,0,37,0,1,0,2,6,120.70,0.0,0.901
1504,17361,8,19,15.50,0,1,1,0.0,0,0,...,0,4,0,0,0,1,3,81.00,0.0,0.933
7945,13548,38,15,22.50,2,6,1,0.0,0,0,...,0,67,0,0,0,1,3,149.40,0.0,0.783
10212,29318,15,9,23.50,2,1,2,1.0,0,0,...,0,7,0,2,0,1,3,133.83,0.0,0.855

In [93]:
appointment.reset_index(drop=True, inplace=True)

In [94]:
complete = pd.concat([appointment, customer], axis=1)
complete

,AppointmentID,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,...,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI,PatientID,FirstName,LastName,Email,Age,Username
0,32310,50,10,20.00,1,1,1,0.0,0,0,...,6,96.00,0.0,0.876,1,John,Doe,johndoe@email.com,35,johndoe35
1,13182,47,16,20.25,2,4,2,0.0,0,0,...,6,120.70,0.0,0.901,2,Jane,Smith,janesmith@email.com,28,janesmith28
2,17361,8,19,15.50,0,1,1,0.0,0,0,...,3,81.00,0.0,0.933,3,Robert,Johnson,robertjohnson@email.com,42,robjohn42
3,13548,38,15,22.50,2,6,1,0.0,0,0,...,3,149.40,0.0,0.783,4,Alice,Williams,alicewilliams@email.com,31,alicewilliams31
4,29318,15,9,23.50,2,1,2,1.0,0,0,...,3,133.83,0.0,0.855,5,Michael,Brown,michaelbrown@email.com,45,mikebrown45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,38826,44,25,17.25,0,2,2,0.0,0,0,...,6,85.50,0.0,0.918,146,Karen,Martin,karenmartin@email.com,45,karenm45
146,19784,40,26,19.75,2,5,2,0.0,0,0,...,6,100.30,0.0,0.805,147,Joseph,Anderson,josephanderson@email.com,36,josepha36
147,31699,32,4,23.75,2,3,2,0.0,0,0,...,6,104.55,0.0,0.757,148,Laura,Perez,lauraperez@email.com,31,laurap31
148,15316,16,13,23.25,0,2,2,0.0,0,0,...,6,85.50,0.0,0.926,149,William,Jones,williamjones@email.com,47,williamj47
149,14769,43,21,16.25,0,2,2,0.0,0,0,...,6,139.00,0.0,0.842,150,Mary,Hill,maryhill@email.com,32,maryh32

In [95]:
complete.columns

Index(['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth',
       'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults',
       'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments',
       'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking',
       'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked',
       'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult',
       'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance',
       'CountryofOriginHDI', 'PatientID', 'FirstName', 'LastName', 'Email',
       'Age', 'Username'],
      dtype='object')

In [97]:
patients = complete[['FirstName', 'LastName', 'Email', 'Age', 'Username', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI']]

In [99]:
appointments = complete[['AppointmentID', 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'OnlineBooking', 'AppointmentChanges', 'BookingToConsultDays', 'ParkingSpaceBooked', 'SpecialRequests', 'NoInsurance', 'ExtraExamsPerConsult', 'DoctorAssigned', 'ConsultPriceEuros', '%PaidinAdvance', 'CountryofOriginHDI', 'Username']]

In [100]:
appointments.sort_values(by=['AppointmentID'], inplace=True)
appointments.reset_index(drop=True, inplace=True)
appointments.drop(columns=['AppointmentID'], inplace=True)
appointments

,AppointmentWeekNumber,AppointmentDayOfMonth,AppointmentHour,WeekendConsults,WeekdayConsults,Adults,Children,Babies,AffiliatedPatient,PreviousAppointments,...,BookingToConsultDays,ParkingSpaceBooked,SpecialRequests,NoInsurance,ExtraExamsPerConsult,DoctorAssigned,ConsultPriceEuros,%PaidinAdvance,CountryofOriginHDI,Username
0,47,14,20.75,1,2,2,0.0,0,0,0,...,17,0,1,0,1,6,67.76,0.0,0.926,markm32
1,46,6,22.00,2,2,2,0.0,0,0,0,...,5,0,1,0,1,6,165.75,0.0,0.842,brianh32
2,45,1,18.50,0,5,2,0.0,0,0,0,...,173,0,2,0,0,6,80.10,0.0,0.926,bettyw40
3,12,18,22.50,1,2,2,0.0,0,0,0,...,199,0,1,0,1,6,65.45,0.0,0.936,lisab30
4,33,9,23.50,0,3,3,0.0,0,0,0,...,106,1,2,0,1,3,159.30,0.0,0.898,williamt30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,48,24,16.75,1,3,2,0.0,0,0,0,...,45,0,0,0,1,6,0.00,0.0,0.926,karenth36
146,44,25,17.25,0,2,2,0.0,0,0,0,...,49,0,0,0,1,6,85.50,0.0,0.918,karenm45
147,44,26,19.75,0,2,2,0.0,0,0,0,...,78,0,1,0,2,3,138.60,0.0,0.918,paulaev37
148,44,28,16.75,0,2,1,2.0,0,0,0,...,199,0,0,0,1,4,109.00,0.0,0.842,willev37
149,47,15,21.25,2,5,2,0.0,0,0,0,...,39,0,1,0,1,6,97.40,0.0,0.757,shirleys46

In [103]:
# Export the DataFrame to a CSV file
appointments.to_csv(path + 'appointments.csv', index=True)
patients.to_csv(path + 'patients.csv', index=True)

NOTAS:
- children estรก como float, nรฃo sei se isso vai ser um problema
- appointment hour estรก tipo: 17.75 que รฉ 17h45
- para chegarmos ao appointment week number atravรฉs da data
    - date_object = datetime.strptime(date_string, '%Y-%m-%d')
    - week_number = date_object.strftime('%W')    o chatgpt disse %V
- id dos medicos รฉ um bocado estranho... por haver -1
- hdi temos de fazer a conversรฃo ... acho que pode ser logo no botรฃo... "se ele escolher isto, isto acontece2 com um if
- temos de aplicar robust scaler nas previsรตes
- dados perguntados ou nรฃo ao utilizador:
    - Sim: 'AppointmentWeekNumber', 'AppointmentDayOfMonth', 'AppointmentHour', 'ParkingSpaceBooked', 'SpecialRequests', 'DoctorAssigned', '%PaidinAdvance'
    - Nรฃo (jรก temos): 'WeekendConsults', 'WeekdayConsults', 'Adults', 'Children', 'Babies', 'AffiliatedPatient', 'PreviousAppointments', 'PreviousNoShows', 'LastMinutesLate', 'NoInsurance', 'ExtraExamsPerConsult', 'CountryofOriginHDI (Year-1)'? , 'PatientID'
    - Nรฃo (calculados): 'ConsultPriceEuros', 'OnlineBooking', 'BookingToConsultDays', 'AppointmentChanges', 'CountryofOriginHDI (Year-1)'?




Household adults 
Household children 
Household babies
Want to have a ficha?
Have insurance?
Nationality